# birthday-app
# this file configures the serverless (Lambda) infrastructure that we want to provision on AWS

service: birthday-backend

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1

functions:
  birthdays:
    environment:
      DB_USER: ${opt:DB_USER}
      DB_PASSWORD: ${opt:DB_PASSWORD}
      DB_HOST: ${opt:DB_HOST}
    handler: handler.birthdays  
    events:
      - http:
          path: birthdays
          method: get
          cors: true
      - http:
          path: birthdays/{birthdayID}
          method: delete
          cors: true

